version: "3"
services:
  node14:
    image: node:14.19.0-buster-slim
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/home/node/app
    expose:
      - "8080"
    ports:
      - "8080:8080"
    command: "npm start"